//
// Created by Anton Romanova on 15/02/2022.
//

#ifndef QUORIDOR_SRC_SERVER_SIDE_VIEWS_CONSTANTS_H_
#define QUORIDOR_SRC_SERVER_SIDE_VIEWS_CONSTANTS_H_

#define PORT 559

#endif //QUORIDOR_SRC_SERVER_SIDE_VIEWS_CONSTANTS_H_
