//
// Created by Anton Romanova on 09/12/2021.
//

#ifndef QUORIDOR_SERVER_SIDE_GAME_LOGIC_PIECE_H_
#define QUORIDOR_SERVER_SIDE_GAME_LOGIC_PIECE_H_

class Piece {

};

#endif //QUORIDOR_SERVER_SIDE_GAME_LOGIC_PIECE_H_
