//
// Created by Anton Romanova on 11/02/2022.
//

#ifndef QUORIDOR_SRC_SERVER_SIDE_MODELS_WALL_H_
#define QUORIDOR_SRC_SERVER_SIDE_MODELS_WALL_H_

class Wall {

};

#endif //QUORIDOR_SRC_SERVER_SIDE_MODELS_WALL_H_
