//
// Created by Anton Romanova on 10/12/2021.
//

#ifndef QUORIDOR_SERVER_SIDE_GAME_LOGIC_BOARD_POSITION_H_
#define QUORIDOR_SERVER_SIDE_GAME_LOGIC_BOARD_POSITION_H_

struct Point {
  unsigned x, y;
};

#endif //QUORIDOR_SERVER_SIDE_GAME_LOGIC_BOARD_POSITION_H_
