//
// Created by Anton Romanova on 09/12/2021.
//

#ifndef QUORIDOR_COMMON_GAME_LOGIC_CONSTANTS_H_
#define QUORIDOR_COMMON_GAME_LOGIC_CONSTANTS_H_

constexpr int QUORIDOR_BOARD_HEIGHT = 9;
constexpr int QUORIDOR_BOARD_WIDTH = 9;

#endif //QUORIDOR_COMMON_GAME_LOGIC_CONSTANTS_H_
