//
// Created by Anton Romanova on 17/02/2022.
//

#ifndef QUORIDOR_SRC_COMMON_CONSTANTS_H_
#define QUORIDOR_SRC_COMMON_CONSTANTS_H_

#define SERVER_PORT 559

// username
#define MAX_USERNAME_SIZE 32
#define MIN_USERNAME_SIZE 3
#define USERNAME_VALID_SPECIAL_CHARS {'-', '_'}

// password
#define MIN_PASSWORD_LENGTH 8
#define MAX_PASSWORD_LENGTH 64

#endif //QUORIDOR_SRC_COMMON_CONSTANTS_H_
